### PR TITLE
Suggested design for buttons 

### PR DESCRIPTION
**Pull request by Adi-204**
The below is suggested design for buttons. I also installed flowbite in project.

Issue - https://github.com/metakgp/travel-buddy/issues/2

image

### CODE REVIEW

**Comment by harshkhandeparkar** [comment]
Where is flowbite used and why?

**Comment by Adi-204** [comment]
Installing Flowbite is not mandatory but by installing it in project will help in modify Flowbite's default styles for future use. It simplifies collaboration with other developers, as they can install the exact same version by running npm install. 
If you want to I can remove flowbite from Project Dependencies.

**Comment by Adi-204** [comment]
Thank you for the guidance! I'll remove Flowbite from the project dependencies and ensure the PR focuses solely on the relevant changes. Let me know if there's anything else you'd like me to address

**Review by saharsh-agrawal — CHANGES_REQUESTED** [review]
Add animation transitions and add similiar designs to buttons on other pages as well.

**Comment by Adi-204** [comment]
Changed Design of All Buttons.

**Review by saharsh-agrawal — COMMENTED** [review]
Please try and add transition animations too.

**Comment by Adi-204** [comment]
What do you mean by "add transition animations" with respect to button ? 
On hover their are effects already applied. 
Can you please specify what exactly you want ?

**Review by saharsh-agrawal — APPROVED** [review]

**Comment by saharsh-agrawal** [comment]
The button changes immediately on hover. Try and implement a transition time of let's say 0.5s

**Comment by saharsh-agrawal** [comment]
The transition isn't working and it isn't even supposed to work on colour-change effects. So merging this for now.

**Pull request merged**
